[package]
name = "hexbitbrush"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hex = "0.4.3"
reduce = "0.1.5"

[dev-dependencies]
k9 = "0.11.6"
